name: connectivity_helper
description: "A package has implements connectivity_plus and local_session_timeout. build for esier use"
version: 1.0.1

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^6.1.0
  local_session_timeout: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


